### ISSUE TITLE
Deploy App Service without public facing endpoint

### ISSUE THREAD

**Issue by tsolanki** [Microsoft/Azure-SQL-DB-auditing-OMS-integration#10]
I would like to use this application to ingest SQL Data Warehouse logs into OMS but, due to security concerns, do not want a public url to be created from this. What mechanisms can I use to accomplish this? Is it as simple as putting it in a VNet or are there additional steps to take?

**Comment by TomerWeisberg** [comment]
Hi tsolanki.

Azure SQL DW is still not supporting auditing to Azure blobs and therefore this solution will not work for you. We are getting close to shipping this and also better OMS integration which will not require the user to deploy this solution. If you want to join our preview when it will be ready, you should send me an email to tomerw at Microsoft dot com.

Thanks,
Tomer (MSFT).
