### ISSUE TITLE
Webjob failed to load audit logs to OMS due to insufficient space

### ISSUE THREAD

**Issue by Mishtry** [Microsoft/Azure-SQL-DB-auditing-OMS-integration#23]
Hi,

It's been more than a week now since I rebuilt the web app to push our SQL audit logs to OMS. After a couple of hours, web job has failed to continue and getting the error below. I already raised a ticket with Microsoft but they directed me here to raise the issue. They stated that the path in the error is not in any of their OMS servers. 

OMS Information: 0 : Was not able to delete file: D:\home\site\wwwroot\u400yj5k.5s2.xel. Reason: There is not enough space on the disk.

**Comment by GalGrinblat** [comment]
Hi Mishtry, 
As a workaround I will suggest to delete files by yourself using the Kudu tools:
1. Go to your web app blade in the Azure portal
2. Look for "Advanced Tools"
3. Select "Debug console" -> "CMD"
4. Find the bad files and delete them
If the app was in bad state for a while you can delete the States.json file as well, it will have the same effect as redeploying the app.

**Comment by Mishtry** [comment]
Hi,

Thank you for your email. I am not in Kudu tool. Do you have the exact location of the file States.json?

Note that insufficient space error is no longer coming through after we scaled up the Web App to B1 App service plan.  We are, however, facing another one in which not all the audit logs are getting pulled to OMS due to invalid format.

[07/23/2018 03:24:59 > 2c204d: INFO] Failed processing audit logs for: <server>/chasqlcomspd_2018-07-21_08:00.34/. Reason: The given path's format is not supported.

Regards,
May Lozano

DBA & Application Support | IT

350 Wellington Road, Mulgrave, Victoria 3170 Australia
M +61 428 796 538
E May.Lozano@city-holdings.com.au<mailto:May.Lozano@city-holdings.com.au>
W www.city-holdings.com.au<http://www.city-holdings.com.au>

[cid:image001.png@01D4228D.079CD9C0]



Our People are the Soul of our City

Follow us on LinkedIn<https://www.linkedin.com/company/city-holdings-australia>

**Comment by GalGrinblat** [comment]
@Mishtry Hi,
We recently added OMS as a built in audit target you can set from the auditing setting of your SQL Server or database. more info here - https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing#subheading-2
